### ISSUE TITLE
[Feature request] Native 3D Vision output modes (Direct3D 9 or 11)

### ISSUE THREAD

**Issue by ThreeDeeJay** [oneup03/VRto3D#2]
SBS and TAB are great for compatibility with many devices, but it would be much better for our good ol' 3D Vision monitors to get the full, raw frames for each eye for a crystal clear image.
There's already some plugins that support DX9/DX11 output modes like [geo-11](https://helixmod.blogspot.com/2022/06/announcing-new-geo-11-3d-driver.html), [VK3DVision](https://github.com/helifax/Vk3DVision-Public) and [OpenGL 3D Vision wrapper](https://github.com/helifax/OGL-3DVision-Wrapper) though you might have to contact the the devs ([davegl1234](https://github.com/davegl1234), [Helifax](https://github.com/helifax) and [bo3b](https://github.com/bo3b)) for guiadance on implementing it.
Perhaps these might also help: 
https://github.com/bo3b/3D-Vision-Direct
https://developer.download.nvidia.com/whitepapers/2010/3DV_BestPracticesGuide.pdf

**Comment by oneup03** [comment]
With the current implementation, I don't think this is possible. This driver just tells Steam VR where and how to draw the left and right eye frames. Steam VR then does all the rendering. 

A more complicated implementation using IVRDriverDirectModeComponent might be possible, but I'm not sure.

**Comment by ThreeDeeJay** [comment]
Ohh, I see. I got this whole thing backwards.
Besides compatibility, I'm also worried about overhead, so I'd imagine we'd want the least possible hoops to jump between the renderer and the 3D display, but yeah this does seem a lot more complicated now.

**Comment by oneup03** [comment]
Found a workaround way to render in 3DVision and updated the README. It doesn't work great due to using old drivers and those being incompatible with many DX12 games.

Haven't had any luck with the IVRDriverDirectModeComponent yet. I think it's theoretically possible, but all the code for DX11->DX9 Direct is closed source.

**Comment by ThreeDeeJay** [comment]
Since https://github.com/oneup03/VRto3D/commit/0acb098243dec736fd496e35c0e17bc43b631262 already added basic support, I'll go ahead and close this issue.👌 
Thanks again! 👍
